package com.frenkel.finnhub_client.models

enum class ExchangeTicker(
    val code: String,
    val exchangeName: String,
    val mic: String
) {
    AD("AD", "ABU DHABI SECURITIES EXCHANGE", "XADS"),
    AQ("AQ", "Aquis Exchange", "AQSE"),
    AS("AS", "NYSE EURONEXT - EURONEXT AMSTERDAM", "XAMS"),
    AT("AT", "ATHENS EXCHANGE S.A. CASH MARKET", "ASEX"),
    AX("AX", "ASX - ALL MARKETS", "XASX"),
    BA("BA", "BOLSA DE COMERCIO DE BUENOS AIRES", "XBUE"),
    BC("BC", "BOLSA DE VALORES DE COLOMBIA", "XBOG"),
    BD("BD", "BUDAPEST STOCK EXCHANGE", "XBUD"),
    BE("BE", "BOERSE BERLIN", "XBER"),
    BH("BH", "BAHRAIN BOURSE", "XBAH"),
    BK("BK", "STOCK EXCHANGE OF THAILAND", "XBKK"),
    BO("BO", "BSE LTD", "XBOM"),
    BR("BR", "NYSE EURONEXT - EURONEXT BRUSSELS", "XBRU"),
    CA("CA", "Egyptian Stock Exchange", "XCAI"),
    CN("CN", "CANADIAN NATIONAL STOCK EXCHANGE", "XCNQ"),
    CO("CO", "OMX NORDIC EXCHANGE COPENHAGEN A/S", "XCSE"),
    CR("CR", "CARACAS STOCK EXCHANGE", "BVCA"),
    CS("CS", "CASABLANCA STOCK EXCHANGE", "XCAS"),
    DB("DB", "DUBAI FINANCIAL MARKET", "XDFM"),
    DE("DE", "XETRA", "XETR"),
    DS("DS", "Dhaka Stock Exchange", "XDHA"),
    DU("DU", "BOERSE DUESSELDORF", "XDUS"),
    F("F", "DEUTSCHE BOERSE AG", "XFRA"),
    HE("HE", "NASDAQ OMX HELSINKI LTD", "XHEL"),
    HK("HK", "HONG KONG EXCHANGES AND CLEARING LTD", "XHKG"),
    HM("HM", "HANSEATISCHE WERTPAPIERBOERSE HAMBURG", "XHAM"),
    IC("IC", "NASDAQ OMX ICELAND", "XICE"),
    IR("IR", "IRISH STOCK EXCHANGE - ALL MARKET", "XDUB"),
    IS("IS", "BORSA ISTANBUL", "XIST"),
    JK("JK", "INDONESIA STOCK EXCHANGE", "XIDX"),
    JO("JO", "JOHANNESBURG STOCK EXCHANGE", "XJSE"),
    KL("KL", "BURSA MALAYSIA", "XKLS"),
    KQ("KQ", "KOREA EXCHANGE (KOSDAQ)", "XKOS"),
    KS("KS", "KOREA EXCHANGE (STOCK MARKET)", "XKRX"),
    KW("KW", "Kuwait Stock Exchange", "XKUW"),
    L("L", "LONDON STOCK EXCHANGE", "XLON"),
    LN("LN", "Euronext London", "XLDN"),
    LS("LS", "NYSE EURONEXT - EURONEXT LISBON", "XLIS"),
    MC("MC", "BOLSA DE MADRID", "XMAD"),
    ME("ME", "MOSCOW EXCHANGE", "MISX"),
    MI("MI", "Italian Stock Exchange", "XMIL"),
    MU("MU", "BOERSE MUENCHEN", "XMUN"),
    MX("MX", "BOLSA MEXICANA DE VALORES (MEXICAN STOCK EXCHANGE)", "XMEX"),
    NE("NE", "AEQUITAS NEO EXCHANGE", "NEOE"),
    NL("NL", "Nigerian Stock Exchange", "XNSA"),
    NS("NS", "NATIONAL STOCK EXCHANGE OF INDIA", "XNSE"),
    NZ("NZ", "NEW ZEALAND EXCHANGE LTD", "XNZE"),
    OL("OL", "OSLO BORS ASA", "XOSL"),
    PA("PA", "NYSE EURONEXT - MARCHE LIBRE PARIS", "XPAR"),
    PM("PM", "Philippine Stock Exchange", "XPHS"),
    PR("PR", "PRAGUE STOCK EXCHANGE", "XPRA"),
    QA("QA", "QATAR EXCHANGE", "DSMD"),
    RG("RG", "NASDAQ OMX RIGA", "XRIS"),
    SA("SA", "Brazil Bolsa - Sao Paolo", "BVMF"),
    SG("SG", "BOERSE STUTTGART", "XSTU"),
    SI("SI", "SINGAPORE EXCHANGE", "XSES"),
    SN("SN", "SANTIAGO STOCK EXCHANGE", "XSGO"),
    SR("SR", "SAUDI STOCK EXCHANGE", "XSAU"),
    SS("SS", "SHANGHAI STOCK EXCHANGE", "XSHG"),
    ST("ST", "NASDAQ OMX NORDIC STOCKHOLM", "XSTO"),
    SW("SW", "SWISS EXCHANGE", "XSWX"),
    SZ("SZ", "SHENZHEN STOCK EXCHANGE", "XSHE"),
    T("T", "TOKYO STOCK EXCHANGE-TOKYO PRO MARKET", "XJPX"),
    TA("TA", "TEL AVIV STOCK EXCHANGE", "XTAE"),
    TL("TL", "NASDAQ OMX TALLINN", "XTAL"),
    TO("TO", "TORONTO STOCK EXCHANGE", "XTSE"),
    TW("TW", "TAIWAN STOCK EXCHANGE", "XTAI"),
    TWO("TWO", "TPEx", "ROCO"),
    TU("TU", "Turquoise", "TRQX"),
    US("US", "US exchanges (NYSE, Nasdaq)", "XNYS,XASE,BATS,ARCX,XNMS,XNCM,XNGS,IEXG,XNAS,OTCM,OOTC"),
    V("V", "TSX VENTURE EXCHANGE - NEX", "XTSX"),
    VI("VI", "Vienna Stock Exchange", "XWBO"),
    VN("VN", "Vietnam exchanges including HOSE, HNX and UPCOM", "HSTC,XSTC"),
    VS("VS", "NASDAQ OMX VILNIUS", "XLIT"),
    WA("WA", "WARSAW STOCK EXCHANGE/EQUITIES/MAIN MARKET", "XWAR"),
    XA("XA", "CBOE Australia", "CXAP"),
    HA("HA", "Hanover Stock Exchange", "XHAN"),
    SX("SX", "DEUTSCHE BOERSE Stoxx", ""),
    TG("TG", "DEUTSCHE BOERSE TradeGate", "XGAT"),
    SC("SC", "BOERSE_FRANKFURT_ZERTIFIKATE", ""),
    SL("SL", "Spotlight Stock Market", "XSAT");
}
